### PR TITLE
add dependencies to turn on BUILD_SHARED_LIBS

### PR DESCRIPTION
**Pull request by weiyuan-jiang**

### CODE REVIEW

**Review by tclune — DISMISSED** [review]

**Comment by tclune** [comment]
Not sure if the workflow issues are real.  Hopefully shared libs are not breaking things.

**Comment by weiyuan-jiang** [comment]
> Not sure if the workflow issues are real. Hopefully shared libs are not breaking things.

 It should not break things. However it should go with the new sparse checkout in GEOSgcm.

**Comment by mathomp4** [comment]
Note: I am not sure this will ever pass CI. Why, well, since it needs changes in the fixture itself to build...changes that are in the sparsing at the `mepo clone` time. But by the time CI can apply anything, the sparsing has already happened.

**Comment by mathomp4** [comment]
Okay. GNU can build with this and a full test of all `feature/wjiang/turn_on_build_shared_libs` branches seems to be zero-diff. I will start the process. First off, we need this released.

**Review by mathomp4 — APPROVED** [review]
Tested and approved.

**Pull request merged**
