### PR TITLE
Replacing crtm 2.3.0 with 2.4.0 + NCEP minor IR fix + Reconfigured Cloud detection for CrIS-FSR 

### PR DESCRIPTION
**Pull request by gmao-wgu**
This PR was created on top of GEOSadas-5_29_5 with the updated CRTM from version 2.3.0 to 2.4.0 plus NCEP minor IR bug fix. gmao_global_satinfo.rc was also updated to reflect both  reconfigured cloud detection for CrIS-FSR and reconfigured gross-check for AIRS, IASI and CrIS-FSR.

### CODE REVIEW

**Comment by mathomp4** [comment]
@gmao-wgu Your labels are a bit confusing. Is the PR zero-diff or not? I'm imagining it isn't (lots of changes...)

**Comment by gmao-wgu** [comment]
> @gmao-wgu Your labels are a bit confusing. Is the PR zero-diff or not? I'm imagining it isn't (lots of changes...)

I thought my PR did not cause any structural change, but not zero diff. My bad.

**Review by rtodling — COMMENTED** [review]
Wei, there is only one thing that needs a little clarification:

I think the CMakeLists as you have it now bypasses fixes that Matt put in to address the occasional issue w/ compilation error of CRTM_module ... check diff at the bottom of CMakeLists

Perhaps Matt can help looking over this.

Also, the top few lines of the CMake have been commented out with a comment stating no understanding for the reasons those lines were there ... I think here too, Matt might be able to clarify.

**Comment by mathomp4** [comment]
> Wei, there is only one thing that needs a little clarification:
> 
> I think the CMakeLists as you have it now bypasses fixes that Matt put in to address the occasional issue w/ compilation error of CRTM_module ... check diff at the bottom of CMakeLists
> 
> Perhaps Matt can help looking over this.

@gmao-wgu I agree with @rtodling  It's possible ye olde `ADA_Module.F90` no longer has an issue with debug, but until we can try it out, you should make the end of the CMakeLists look like:

```cmake
if (CMAKE_Fortran_COMPILER_ID MATCHES Intel)
  set (CMAKE_Fortran_FLAGS_RELEASE "-free ${FOPT2} ${LITTLE_ENDIAN} ${BYTERECLEN}")
  if (CMAKE_BUILD_TYPE MATCHES Debug)
    message(WARNING "Intel Compiler and our debugging flags have issues with ADA_Module.f90. So for now we turn off checking compiling ADA_Module.f90")
    set_source_files_properties(ADA_Module.f90 PROPERTIES COMPILE_OPTIONS -nocheck)
  endif ()
endif ()
```

This code just says "If Intel and Debug, compile `ADA_Module.F90` with no check flags"

> 
> Also, the top few lines of the CMake have been commented out with a comment stating no understanding for the reasons those lines were there ... I think here too, Matt might be able to clarify.

These lines:
```cmake
# no idea why this is not a Fortran file?
#add_custom_command (
#  OUTPUT CRTM_Module.F90
#  COMMAND cp ${CMAKE_CURRENT_SOURCE_DIR}/CRTM_Module.fpp CRTM_Module.F90
#  WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
#  )
```
should just be deleted. It looks like in CTRM 2.4.0 they are no longer using `CRTM_Module.fpp` so this bit of CMake is redundant.

**Comment by rtodling** [comment]
Thanks for the input Matt.

Wei: can you add make the changes as suggested by Matt, and commit them? thanks.

**Comment by mathomp4** [comment]
> Thanks for the input Matt.
> 
> Wei: can you add make the changes as suggested by Matt, and commit them? thanks.

I could do it if you like? Would be pretty quick for me to do so.

**Comment by gmao-wgu** [comment]
> > Thanks for the input Matt.
> > Wei: can you add make the changes as suggested by Matt, and commit them? thanks.
> 
> I could do it if you like? Would be pretty quick for me to do so.

Matt, I am sorry I could not do this today. Of course, go ahead. Thanks!

**Comment by mathomp4** [comment]
> > > Thanks for the input Matt.
> > > Wei: can you add make the changes as suggested by Matt, and commit them? thanks.
> > 
> > 
> > I could do it if you like? Would be pretty quick for me to do so.
> 
> Matt, I am sorry I could not do this today. Of course, go ahead. Thanks!

Done.

**Comment by gmao-wgu** [comment]
> Thanks for the input Matt.
> 
> Wei: can you add make the changes as suggested by Matt, and commit them? thanks.

Ricardo,  Today is Jedi Wednesday, I could do it tomorrow or this evening. Thanks.

**Comment by rtodling** [comment]
I just gave this a try and this looks fine with me.

**Comment by rtodling** [comment]
Matt: I don't have review powers of NCEP_Shared - I wish I had ... can you pls approve and promote this to develop/main? 
Thanks

**Review by rtodling — APPROVED** [review]
All good by me - run just fine for me.

**Review by mathomp4 — APPROVED** [review]
Approve for CMake

**Comment by mathomp4** [comment]
> Matt: I don't have review powers of NCEP_Shared - I wish I had ... can you pls approve and promote this to develop/main? Thanks

@rtodling Sure. I'll merge in. Would you like a new release as well?

**Comment by mathomp4** [comment]
> > Matt: I don't have review powers of NCEP_Shared - I wish I had ... can you pls approve and promote this to develop/main? Thanks
> 
> @rtodling Sure. I'll merge in. Would you like a new release as well?

@rtodling I made a release here: https://github.com/GEOS-ESM/NCEP_Shared/releases/tag/v1.3.0

Just to be safe. If you'd prefer this as v2.0.0, just let me know and I can remake it. (All depends on how you'd like to number it!)

**Comment by rtodling** [comment]
Matt: thank you. Can you make this version v1.3.0 for NCEP_Shared?

**Comment by mathomp4** [comment]
> Matt: thank you. Can you make this version v1.3.0 for NCEP_Shared?

It is there: https://github.com/GEOS-ESM/NCEP_Shared/releases/tag/v1.3.0

**Pull request merged**
